import type { Card } from './types';

// ===== 人物卡 (80张) =====
export const CHARACTER_CARDS: Card[] = [
  // 先秦-秦汉
  { id: 'CH001', name: '秦始皇', type: 'character', era: '秦', tags: ['君主','秦'], attributes: { political: 3, economic: 2, military: 3, cultural: 1 }, description: '书同文，车同轨' },
  { id: 'CH002', name: '李斯', type: 'character', era: '秦', tags: ['谋士','秦'], attributes: { political: 3, economic: 1, military: 0, cultural: 1 }, description: '法家代表' },
  { id: 'CH003', name: '王翦', type: 'character', era: '秦', tags: ['将领','秦'], attributes: { political: 0, economic: 0, military: 4, cultural: 0 }, description: '破楚灭赵' },
  { id: 'CH004', name: '刘邦', type: 'character', era: '汉', tags: ['君主','汉'], attributes: { political: 3, economic: 2, military: 1, cultural: 1 }, description: '布衣天子' },
  { id: 'CH005', name: '项羽', type: 'character', era: '楚', tags: ['将领','楚'], attributes: { political: 1, economic: 0, military: 5, cultural: 0 }, description: '力拔山兮' },
  { id: 'CH006', name: '韩信', type: 'character', era: '汉', tags: ['将领','汉'], attributes: { political: 0, economic: 0, military: 5, cultural: 1 }, description: '兵仙' },
  { id: 'CH007', name: '张良', type: 'character', era: '汉', tags: ['谋士','汉'], attributes: { political: 3, economic: 0, military: 0, cultural: 2 }, description: '运筹帷幄' },
  { id: 'CH008', name: '萧何', type: 'character', era: '汉', tags: ['谋士','汉'], attributes: { political: 3, economic: 3, military: 0, cultural: 1 }, description: '镇国抚民' },
  { id: 'CH009', name: '汉武帝', type: 'character', era: '汉', tags: ['君主','汉'], attributes: { political: 4, economic: 2, military: 4, cultural: 2 }, description: '北逐匈奴', image: '/assets/cards/character_ch001.png' },
  { id: 'CH010', name: '卫青', type: 'character', era: '汉', tags: ['将领','汉'], attributes: { political: 0, economic: 0, military: 4, cultural: 0 }, description: '七战七捷' },
  { id: 'CH011', name: '霍去病', type: 'character', era: '汉', tags: ['将领','汉'], attributes: { political: 0, economic: 0, military: 5, cultural: 0 }, description: '封狼居胥' },
  { id: 'CH012', name: '张骞', type: 'character', era: '汉', tags: ['探险家','汉'], attributes: { political: 0, economic: 2, military: 0, cultural: 2 }, description: '凿空西域' },
  { id: 'CH013', name: '司马迁', type: 'character', era: '汉', tags: ['史家','汉'], attributes: { political: 1, economic: 0, military: 0, cultural: 4 }, description: '著《史记》' },
  { id: 'CH014', name: '王昭君', type: 'character', era: '汉', tags: ['和亲','汉'], attributes: { political: 2, economic: 0, military: 0, cultural: 2 }, description: '出塞和亲' },
  { id: 'CH015', name: '刘秀', type: 'character', era: '东汉', tags: ['君主','东汉'], attributes: { political: 4, economic: 3, military: 4, cultural: 2 }, description: '光武中兴' },
  { id: 'CH016', name: '班超', type: 'character', era: '东汉', tags: ['将领','东汉'], attributes: { political: 2, economic: 1, military: 3, cultural: 1 }, description: '投笔从戎' },
  { id: 'CH017', name: '蔡伦', type: 'character', era: '东汉', tags: ['发明家','东汉'], attributes: { political: 0, economic: 1, military: 0, cultural: 4 }, description: '改进造纸' },
  { id: 'CH018', name: '张衡', type: 'character', era: '东汉', tags: ['科学家','东汉'], attributes: { political: 0, economic: 0, military: 0, cultural: 5 }, description: '地动仪' },
  { id: 'CH019', name: '曹操', type: 'character', era: '三国', tags: ['君主','魏'], attributes: { political: 3, economic: 1, military: 4, cultural: 2 }, description: '乱世奸雄' },
  { id: 'CH020', name: '诸葛亮', type: 'character', era: '三国', tags: ['谋士','蜀'], attributes: { political: 4, economic: 2, military: 3, cultural: 4 }, description: '鞠躬尽瘁', image: '/assets/cards/character_ch020.png' },
  { id: 'CH021', name: '周瑜', type: 'character', era: '三国', tags: ['将领','吴'], attributes: { political: 2, economic: 0, military: 4, cultural: 2 }, description: '火烧赤壁' },
  { id: 'CH022', name: '孙权', type: 'character', era: '三国', tags: ['君主','吴'], attributes: { political: 3, economic: 3, military: 2, cultural: 2 }, description: '坐断东南' },
  { id: 'CH023', name: '司马懿', type: 'character', era: '三国', tags: ['谋士','魏'], attributes: { political: 4, economic: 0, military: 3, cultural: 1 }, description: '隐忍待发' },
  { id: 'CH024', name: '关羽', type: 'character', era: '三国', tags: ['将领','蜀'], attributes: { political: 0, economic: 0, military: 4, cultural: 1 }, description: '武圣' },
  { id: 'CH025', name: '华佗', type: 'character', era: '汉', tags: ['医者','汉'], attributes: { political: 0, economic: 0, military: 0, cultural: 3 }, description: '外科鼻祖' },
  // 魏晋-隋唐
  { id: 'CH026', name: '曹操', type: 'character', era: '魏', tags: ['君主','魏'], attributes: { political: 3, economic: 1, military: 4, cultural: 2 }, description: '建安风骨' },
  { id: 'CH027', name: '曹植', type: 'character', era: '魏', tags: ['文人','魏'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '七步成诗' },
  { id: 'CH028', name: '王羲之', type: 'character', era: '晋', tags: ['书家','晋'], attributes: { political: 0, economic: 0, military: 0, cultural: 5 }, description: '书圣' },
  { id: 'CH029', name: '谢安', type: 'character', era: '晋', tags: ['谋士','晋'], attributes: { political: 3, economic: 1, military: 2, cultural: 3 }, description: '淝水定国' },
  { id: 'CH030', name: '谢玄', type: 'character', era: '晋', tags: ['将领','晋'], attributes: { political: 0, economic: 0, military: 4, cultural: 1 }, description: '北府兵' },
  { id: 'CH031', name: '拓跋宏', type: 'character', era: '北魏', tags: ['君主','北魏'], attributes: { political: 4, economic: 2, military: 1, cultural: 3 }, description: '孝文帝改革' },
  { id: 'CH032', name: '隋炀帝', type: 'character', era: '隋', tags: ['君主','隋'], attributes: { political: 2, economic: 4, military: 2, cultural: 2 }, description: '大运河' },
  { id: 'CH033', name: '唐太宗', type: 'character', era: '唐', tags: ['君主','唐'], attributes: { political: 4, economic: 3, military: 4, cultural: 4 }, description: '贞观之治' },
  { id: 'CH034', name: '魏徵', type: 'character', era: '唐', tags: ['谏臣','唐'], attributes: { political: 4, economic: 0, military: 0, cultural: 2 }, description: '以人为镜' },
  { id: 'CH035', name: '房玄龄', type: 'character', era: '唐', tags: ['谋士','唐'], attributes: { political: 3, economic: 1, military: 0, cultural: 2 }, description: '贞观名相' },
  { id: 'CH036', name: '杜如晦', type: 'character', era: '唐', tags: ['谋士','唐'], attributes: { political: 3, economic: 1, military: 0, cultural: 2 }, description: '房谋杜断' },
  { id: 'CH037', name: '李靖', type: 'character', era: '唐', tags: ['将领','唐'], attributes: { political: 0, economic: 0, military: 5, cultural: 1 }, description: '卫国公' },
  { id: 'CH038', name: '武则天', type: 'character', era: '唐', tags: ['君主','唐'], attributes: { political: 5, economic: 2, military: 2, cultural: 3 }, description: '唯一女帝', image: '/assets/cards/character_ch038.png' },
  { id: 'CH039', name: '狄仁杰', type: 'character', era: '唐', tags: ['法官','唐'], attributes: { political: 4, economic: 0, military: 0, cultural: 2 }, description: '神探' },
  { id: 'CH040', name: '李白', type: 'character', era: '唐', tags: ['诗人','唐'], attributes: { political: 0, economic: 0, military: 0, cultural: 5 }, description: '诗仙', image: '/assets/cards/character_ch040.png' },
  { id: 'CH041', name: '杜甫', type: 'character', era: '唐', tags: ['诗人','唐'], attributes: { political: 1, economic: 0, military: 0, cultural: 5 }, description: '诗圣' },
  { id: 'CH042', name: '白居易', type: 'character', era: '唐', tags: ['诗人','唐'], attributes: { political: 1, economic: 0, military: 0, cultural: 4 }, description: '长恨歌' },
  { id: 'CH043', name: '玄奘', type: 'character', era: '唐', tags: ['僧侣','唐'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '西行取经' },
  { id: 'CH044', name: '安禄山', type: 'character', era: '唐', tags: ['叛将','唐'], attributes: { political: 1, economic: 0, military: 4, cultural: 0 }, description: '安史之乱' },
  { id: 'CH045', name: '郭子仪', type: 'character', era: '唐', tags: ['将领','唐'], attributes: { political: 2, economic: 0, military: 5, cultural: 1 }, description: '中兴名将' },
  // 宋元
  { id: 'CH046', name: '赵匡胤', type: 'character', era: '宋', tags: ['君主','宋'], attributes: { political: 4, economic: 2, military: 3, cultural: 2 }, description: '杯酒释兵权' },
  { id: 'CH047', name: '包拯', type: 'character', era: '宋', tags: ['法官','宋'], attributes: { political: 4, economic: 0, military: 0, cultural: 1 }, description: '包青天' },
  { id: 'CH048', name: '范仲淹', type: 'character', era: '宋', tags: ['改革家','宋'], attributes: { political: 4, economic: 1, military: 1, cultural: 3 }, description: '庆历新政' },
  { id: 'CH049', name: '王安石', type: 'character', era: '宋', tags: ['改革家','宋'], attributes: { political: 5, economic: 4, military: 1, cultural: 3 }, description: '熙宁变法' },
  { id: 'CH050', name: '司马光', type: 'character', era: '宋', tags: ['史家','宋'], attributes: { political: 3, economic: 0, military: 0, cultural: 4 }, description: '资治通鉴' },
  { id: 'CH051', name: '苏轼', type: 'character', era: '宋', tags: ['文人','宋'], attributes: { political: 1, economic: 0, military: 0, cultural: 5 }, description: '东坡居士' },
  { id: 'CH052', name: '李清照', type: 'character', era: '宋', tags: ['词人','宋'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '易安词' },
  { id: 'CH053', name: '岳飞', type: 'character', era: '宋', tags: ['将领','宋'], attributes: { political: 1, economic: 0, military: 5, cultural: 1 }, description: '精忠报国' },
  { id: 'CH054', name: '韩世忠', type: 'character', era: '宋', tags: ['将领','宋'], attributes: { political: 0, economic: 0, military: 4, cultural: 0 }, description: '黄天荡' },
  { id: 'CH055', name: '秦桧', type: 'character', era: '宋', tags: ['奸臣','宋'], attributes: { political: -2, economic: 0, military: 0, cultural: 0 }, description: '陷害岳飞' },
  { id: 'CH056', name: '毕昇', type: 'character', era: '宋', tags: ['发明家','宋'], attributes: { political: 0, economic: 1, military: 0, cultural: 5 }, description: '活字印刷' },
  { id: 'CH057', name: '沈括', type: 'character', era: '宋', tags: ['科学家','宋'], attributes: { political: 0, economic: 1, military: 0, cultural: 5 }, description: '梦溪笔谈' },
  { id: 'CH058', name: '成吉思汗', type: 'character', era: '元', tags: ['君主','元'], attributes: { political: 2, economic: 1, military: 5, cultural: 1 }, description: '一代天骄' },
  { id: 'CH059', name: '忽必烈', type: 'character', era: '元', tags: ['君主','元'], attributes: { political: 3, economic: 3, military: 4, cultural: 2 }, description: '建元' },
  { id: 'CH060', name: '关汉卿', type: 'character', era: '元', tags: ['剧作家','元'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '窦娥冤' },
  // 明清-近代
  { id: 'CH061', name: '朱元璋', type: 'character', era: '明', tags: ['君主','明'], attributes: { political: 4, economic: 2, military: 3, cultural: 1 }, description: '洪武之治' },
  { id: 'CH062', name: '朱棣', type: 'character', era: '明', tags: ['君主','明'], attributes: { political: 4, economic: 3, military: 3, cultural: 3 }, description: '永乐大帝' },
  { id: 'CH063', name: '郑和', type: 'character', era: '明', tags: ['航海家','明'], attributes: { political: 0, economic: 4, military: 1, cultural: 2 }, description: '七下西洋' },
  { id: 'CH064', name: '解缙', type: 'character', era: '明', tags: ['文人','明'], attributes: { political: 1, economic: 0, military: 0, cultural: 4 }, description: '永乐大典' },
  { id: 'CH065', name: '于谦', type: 'character', era: '明', tags: ['将领','明'], attributes: { political: 3, economic: 0, military: 4, cultural: 1 }, description: '北京保卫战' },
  { id: 'CH066', name: '王阳明', type: 'character', era: '明', tags: ['哲学家','明'], attributes: { political: 2, economic: 0, military: 1, cultural: 5 }, description: '心学' },
  { id: 'CH067', name: '张居正', type: 'character', era: '明', tags: ['改革家','明'], attributes: { political: 5, economic: 4, military: 1, cultural: 2 }, description: '一条鞭法' },
  { id: 'CH068', name: '海瑞', type: 'character', era: '明', tags: ['法官','明'], attributes: { political: 4, economic: 0, military: 0, cultural: 1 }, description: '海青天' },
  { id: 'CH069', name: '戚继光', type: 'character', era: '明', tags: ['将领','明'], attributes: { political: 0, economic: 0, military: 5, cultural: 1 }, description: '抗倭' },
  { id: 'CH070', name: '李时珍', type: 'character', era: '明', tags: ['医者','明'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '本草纲目' },
  { id: 'CH071', name: '魏忠贤', type: 'character', era: '明', tags: ['宦官','明'], attributes: { political: -2, economic: 0, military: 0, cultural: 0 }, description: '阉党' },
  { id: 'CH072', name: '袁崇焕', type: 'character', era: '明', tags: ['将领','明'], attributes: { political: 0, economic: 0, military: 4, cultural: 0 }, description: '宁远大捷' },
  { id: 'CH073', name: '吴三桂', type: 'character', era: '清', tags: ['叛将','清'], attributes: { political: 0, economic: 0, military: 3, cultural: 0 }, description: '开关降清' },
  { id: 'CH074', name: '康熙', type: 'character', era: '清', tags: ['君主','清'], attributes: { political: 4, economic: 3, military: 3, cultural: 3 }, description: '康乾盛世' },
  { id: 'CH075', name: '乾隆', type: 'character', era: '清', tags: ['君主','清'], attributes: { political: 3, economic: 4, military: 2, cultural: 3 }, description: '十全武功' },
  { id: 'CH076', name: '曹雪芹', type: 'character', era: '清', tags: ['文人','清'], attributes: { political: 0, economic: 0, military: 0, cultural: 5 }, description: '红楼梦' },
  { id: 'CH077', name: '林则徐', type: 'character', era: '清', tags: ['官员','清'], attributes: { political: 3, economic: 1, military: 1, cultural: 2 }, description: '虎门销烟' },
  { id: 'CH078', name: '曾国藩', type: 'character', era: '清', tags: ['将领','清'], attributes: { political: 3, economic: 2, military: 4, cultural: 2 }, description: '湘军' },
  { id: 'CH079', name: '李鸿章', type: 'character', era: '清', tags: ['官员','清'], attributes: { political: 2, economic: 3, military: 1, cultural: 1 }, description: '洋务运动' },
  { id: 'CH080', name: '孙中山', type: 'character', era: '近代', tags: ['革命家','近代'], attributes: { political: 4, economic: 1, military: 2, cultural: 3 }, description: '辛亥革命' },
  { id: 'CH081', name: '刘备', type: 'character', era: '东汉', tags: ['汉'], attributes: { political: 3, economic: 2, military: 3, cultural: 2 }, description: '仁德之君，三顾茅庐' },
  { id: 'CH082', name: '张飞', type: 'character', era: '东汉', tags: ['汉'], attributes: { political: 0, economic: 0, military: 4, cultural: 1 }, description: '万人敌，长坂坡喝退曹军' },
  { id: 'CH083', name: '黄盖', type: 'character', era: '东汉', tags: ['汉'], attributes: { political: 0, economic: 0, military: 3, cultural: 1 }, description: '苦肉计，火攻赤壁' },
  { id: 'CH084', name: '王维', type: 'character', era: '唐', tags: ['唐'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '诗佛，山水田园诗派代表' },
  { id: 'CH085', name: '孟浩然', type: 'character', era: '唐', tags: ['唐'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '山水田园诗派代表' },
  { id: 'CH086', name: '辛弃疾', type: 'character', era: '南宋', tags: ['宋'], attributes: { political: 1, economic: 0, military: 2, cultural: 5 }, description: '豪放派词宗，文武全才' },
  { id: 'CH087', name: '欧阳修', type: 'character', era: '北宋', tags: ['宋'], attributes: { political: 3, economic: 0, military: 0, cultural: 5 }, description: '北宋文坛领袖' },
  { id: 'CH088', name: '徐达', type: 'character', era: '明', tags: ['明'], attributes: { political: 1, economic: 0, military: 5, cultural: 0 }, description: '明朝开国第一功臣' },
  { id: 'CH089', name: '王勃', type: 'character', era: '唐', tags: ['唐'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '初唐四杰之首' },
  { id: 'CH090', name: '苏洵', type: 'character', era: '北宋', tags: ['宋'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '苏轼之父，三苏之首' },
  { id: 'CH091', name: '苏辙', type: 'character', era: '北宋', tags: ['宋'], attributes: { political: 3, economic: 0, military: 0, cultural: 4 }, description: '苏轼之弟，三苏之一' },
  { id: 'CH092', name: '唐玄宗', type: 'character', era: '唐', tags: ['唐'], attributes: { political: 4, economic: 3, military: 2, cultural: 4 }, description: '开元盛世的开创者' },
  { id: 'CH093', name: '杨贵妃', type: 'character', era: '唐', tags: ['唐'], attributes: { political: 0, economic: 0, military: 0, cultural: 3 }, description: '中国古代四大美女之一' },
  { id: 'CH094', name: '王昭君', type: 'character', era: '西汉', tags: ['汉'], attributes: { political: 2, economic: 0, military: 0, cultural: 2 }, description: '落雁，和亲匈奴' },
  { id: 'CH095', name: '文成公主', type: 'character', era: '唐', tags: ['唐'], attributes: { political: 2, economic: 1, military: 0, cultural: 2 }, description: '入藏和亲，汉藏交流' },
  { id: 'CH096', name: '李清照', type: 'character', era: '南宋', tags: ['宋'], attributes: { political: 0, economic: 0, military: 0, cultural: 5 }, description: '婉约词宗，千古第一才女' },
  { id: 'CH097', name: '陆游', type: 'character', era: '南宋', tags: ['宋'], attributes: { political: 1, economic: 0, military: 1, cultural: 4 }, description: '南宋爱国诗人' },
  { id: 'CH098', name: '唐伯虎', type: 'character', era: '明', tags: ['明'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '江南四大才子之首' },
  { id: 'CH099', name: '郑板桥', type: 'character', era: '清', tags: ['清'], attributes: { political: 1, economic: 0, military: 0, cultural: 4 }, description: '扬州八怪之一，诗书画三绝' },
];

// ===== 物品卡 (40张) =====
export const ITEM_CARDS: Card[] = [
  { id: 'IT001', name: '和氏璧', type: 'item', era: '秦', tags: ['玉器','秦'], attributes: { political: 1, economic: 1, military: 0, cultural: 2 }, description: '完璧归赵', image: '/assets/cards/item_it001.png' },
  { id: 'IT002', name: '传国玉玺', type: 'item', era: '汉', tags: ['信物','汉'], attributes: { political: 3, economic: 0, military: 0, cultural: 1 }, description: '受命于天' },
  { id: 'IT003', name: '兰亭序', type: 'item', era: '晋', tags: ['书法','晋'], attributes: { political: 0, economic: 0, military: 0, cultural: 5 }, description: '天下第一行书' },
  { id: 'IT004', name: '洛神赋图', type: 'item', era: '晋', tags: ['绘画','晋'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '顾恺之' },
  { id: 'IT005', name: '丝绸', type: 'item', era: '汉', tags: ['商品','汉'], attributes: { political: 0, economic: 3, military: 0, cultural: 1 }, description: '丝路商品' },
  { id: 'IT006', name: '茶叶', type: 'item', era: '唐', tags: ['商品','唐'], attributes: { political: 0, economic: 2, military: 0, cultural: 2 }, description: '茶马古道' },
  { id: 'IT007', name: '瓷器', type: 'item', era: '宋', tags: ['商品','宋'], attributes: { political: 0, economic: 3, military: 0, cultural: 2 }, description: '青花瓷' },
  { id: 'IT008', name: '火药配方', type: 'item', era: '唐', tags: ['发明','唐'], attributes: { political: 0, economic: 0, military: 4, cultural: 2 }, description: '四大发明' },
  { id: 'IT009', name: '指南针', type: 'item', era: '宋', tags: ['发明','宋'], attributes: { political: 0, economic: 0, military: 2, cultural: 3 }, description: '四大发明' },
  { id: 'IT010', name: '造纸术', type: 'item', era: '汉', tags: ['发明','汉'], attributes: { political: 0, economic: 0, military: 0, cultural: 5 }, description: '四大发明' },
  { id: 'IT011', name: '活字泥版', type: 'item', era: '宋', tags: ['发明','宋'], attributes: { political: 0, economic: 1, military: 0, cultural: 5 }, description: '毕昇' },
  { id: 'IT012', name: '木牛流马', type: 'item', era: '蜀', tags: ['器械','蜀'], attributes: { political: 0, economic: 2, military: 1, cultural: 2 }, description: '诸葛亮' },
  { id: 'IT013', name: '宝船', type: 'item', era: '明', tags: ['船只','明'], attributes: { political: 0, economic: 2, military: 3, cultural: 1 }, description: '郑和' },
  { id: 'IT014', name: '丈八蛇矛', type: 'item', era: '三国', tags: ['兵器','三国'], attributes: { political: 0, economic: 0, military: 3, cultural: 1 }, description: '张飞' },
  { id: 'IT015', name: '青龙刀', type: 'item', era: '三国', tags: ['兵器','三国'], attributes: { political: 0, economic: 0, military: 3, cultural: 1 }, description: '关羽' },
  { id: 'IT016', name: '孙子兵法', type: 'item', era: '春秋', tags: ['兵书','春秋'], attributes: { political: 0, economic: 0, military: 4, cultural: 3 }, description: '孙武' },
  { id: 'IT017', name: '六韬', type: 'item', era: '周', tags: ['兵书','周'], attributes: { political: 0, economic: 0, military: 3, cultural: 2 }, description: '姜尚' },
  { id: 'IT018', name: '史记', type: 'item', era: '汉', tags: ['史书','汉'], attributes: { political: 1, economic: 0, military: 0, cultural: 5 }, description: '司马迁' },
  { id: 'IT019', name: '资治通鉴', type: 'item', era: '宋', tags: ['史书','宋'], attributes: { political: 2, economic: 0, military: 0, cultural: 4 }, description: '司马光' },
  { id: 'IT020', name: '永乐大典', type: 'item', era: '明', tags: ['类书','明'], attributes: { political: 1, economic: 0, military: 0, cultural: 5 }, description: '解缙' },
  { id: 'IT021', name: '四库全书', type: 'item', era: '清', tags: ['类书','清'], attributes: { political: 2, economic: 0, military: 0, cultural: 4 }, description: '乾隆' },
  { id: 'IT022', name: '红楼梦', type: 'item', era: '清', tags: ['小说','清'], attributes: { political: 0, economic: 0, military: 0, cultural: 5 }, description: '曹雪芹' },
  { id: 'IT023', name: '水浒传', type: 'item', era: '明', tags: ['小说','明'], attributes: { political: 0, economic: 0, military: 1, cultural: 4 }, description: '施耐庵' },
  { id: 'IT024', name: '西游记', type: 'item', era: '明', tags: ['小说','明'], attributes: { political: 0, economic: 0, military: 1, cultural: 4 }, description: '吴承恩' },
  { id: 'IT025', name: '三国演义', type: 'item', era: '明', tags: ['小说','明'], attributes: { political: 0, economic: 0, military: 2, cultural: 4 }, description: '罗贯中' },
  { id: 'IT026', name: '清明上河图', type: 'item', era: '宋', tags: ['绘画','宋'], attributes: { political: 0, economic: 3, military: 0, cultural: 4 }, description: '张择端' },
  { id: 'IT027', name: '本草纲目', type: 'item', era: '明', tags: ['医书','明'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '李时珍' },
  { id: 'IT028', name: '天工开物', type: 'item', era: '明', tags: ['科技','明'], attributes: { political: 0, economic: 3, military: 0, cultural: 3 }, description: '宋应星' },
  { id: 'IT029', name: '梦溪笔谈', type: 'item', era: '宋', tags: ['笔记','宋'], attributes: { political: 0, economic: 1, military: 0, cultural: 5 }, description: '沈括' },
  { id: 'IT030', name: '齐民要术', type: 'item', era: '北魏', tags: ['农书','北魏'], attributes: { political: 0, economic: 4, military: 0, cultural: 2 }, description: '贾思勰' },
  { id: 'IT031', name: '都江堰图纸', type: 'item', era: '秦', tags: ['水利','秦'], attributes: { political: 0, economic: 4, military: 0, cultural: 1 }, description: '李冰' },
  { id: 'IT032', name: '大运河图', type: 'item', era: '隋', tags: ['水利','隋'], attributes: { political: 0, economic: 4, military: 0, cultural: 1 }, description: '隋炀帝' },
  { id: 'IT033', name: '郑国渠图', type: 'item', era: '秦', tags: ['水利','秦'], attributes: { political: 0, economic: 3, military: 0, cultural: 1 }, description: '郑国' },
  { id: 'IT034', name: '灵渠图', type: 'item', era: '秦', tags: ['水利','秦'], attributes: { political: 0, economic: 2, military: 1, cultural: 1 }, description: '史禄' },
  { id: 'IT035', name: '地动仪模型', type: 'item', era: '汉', tags: ['科技','汉'], attributes: { political: 0, economic: 0, military: 0, cultural: 5 }, description: '张衡' },
  { id: 'IT036', name: '浑天仪', type: 'item', era: '汉', tags: ['科技','汉'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '张衡' },
  { id: 'IT037', name: '佛经', type: 'item', era: '唐', tags: ['宗教','唐'], attributes: { political: 0, economic: 0, military: 0, cultural: 3 }, description: '玄奘' },
  { id: 'IT038', name: '琵琶', type: 'item', era: '汉', tags: ['乐器','汉'], attributes: { political: 0, economic: 0, military: 0, cultural: 3 }, description: '王昭君' },
  { id: 'IT039', name: '编钟', type: 'item', era: '周', tags: ['乐器','周'], attributes: { political: 0, economic: 0, military: 0, cultural: 3 }, description: '曾侯乙' },
  { id: 'IT040', name: '青铜鼎', type: 'item', era: '商', tags: ['礼器','商'], attributes: { political: 1, economic: 0, military: 0, cultural: 3 }, description: '司母戊' },
  { id: 'IT041', name: '羽扇纶巾', type: 'item', era: '三国', tags: ['魏'], attributes: { political: 0, economic: 0, military: 0, cultural: 3 }, description: '诸葛亮和周瑜的标志性装束' },
  { id: 'IT042', name: '兰亭序', type: 'item', era: '晋', tags: ['晋'], attributes: { political: 0, economic: 0, military: 0, cultural: 5 }, description: '天下第一行书' },
  { id: 'IT043', name: '出师表', type: 'item', era: '蜀', tags: ['蜀'], attributes: { political: 2, economic: 0, military: 0, cultural: 3 }, description: '诸葛亮的千古名篇' },
  { id: 'IT044', name: '霓裳羽衣', type: 'item', era: '唐', tags: ['唐'], attributes: { political: 0, economic: 0, military: 0, cultural: 3 }, description: '唐代宫廷乐舞的代表' },
  { id: 'IT045', name: '清明上河图', type: 'item', era: '宋', tags: ['宋'], attributes: { political: 0, economic: 3, military: 0, cultural: 4 }, description: '北宋市井繁华的写照' },
  { id: 'IT046', name: '富春山居图', type: 'item', era: '元', tags: ['元'], attributes: { political: 0, economic: 0, military: 0, cultural: 5 }, description: '中国山水画第一神品' },
  { id: 'IT047', name: '永乐大典', type: 'item', era: '明', tags: ['明'], attributes: { political: 2, economic: 0, military: 0, cultural: 5 }, description: '中国古代最大的类书' },
];

// ===== 情景卡 (40张) =====
export const SCENARIO_CARDS: Card[] = [
  { id: 'SC001', name: '丝绸之路', type: 'scenario', era: '汉', tags: ['商路','汉'], attributes: { political: 1, economic: 4, military: 0, cultural: 2 }, description: '东西交汇' },
  { id: 'SC002', name: '茶马古道', type: 'scenario', era: '唐', tags: ['商路','唐'], attributes: { political: 0, economic: 3, military: 0, cultural: 2 }, description: '雪域商路' },
  { id: 'SC003', name: '海上丝路', type: 'scenario', era: '宋', tags: ['商路','宋'], attributes: { political: 0, economic: 4, military: 0, cultural: 1 }, description: '泉州起航' },
  { id: 'SC004', name: '科举考场', type: 'scenario', era: '隋', tags: ['制度','隋'], attributes: { political: 3, economic: 0, military: 0, cultural: 2 }, description: '鲤鱼跃龙门' },
  { id: 'SC005', name: '太学', type: 'scenario', era: '汉', tags: ['教育','汉'], attributes: { political: 1, economic: 0, military: 0, cultural: 3 }, description: '最高学府' },
  { id: 'SC006', name: '白鹿洞书院', type: 'scenario', era: '宋', tags: ['书院','宋'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '朱熹讲学' },
  { id: 'SC007', name: '赤壁战场', type: 'scenario', era: '三国', tags: ['战场','三国'], attributes: { political: 0, economic: 0, military: 4, cultural: 1 }, description: '火烧连营' },
  { id: 'SC008', name: '淝水岸', type: 'scenario', era: '晋', tags: ['战场','晋'], attributes: { political: 0, economic: 0, military: 4, cultural: 1 }, description: '八万破百万' },
  { id: 'SC009', name: '官渡', type: 'scenario', era: '三国', tags: ['战场','三国'], attributes: { political: 0, economic: 0, military: 3, cultural: 0 }, description: '乌巢烧粮' },
  { id: 'SC010', name: '长安城', type: 'scenario', era: '唐', tags: ['都城','唐'], attributes: { political: 2, economic: 2, military: 1, cultural: 3 }, description: '盛世之都' },
  { id: 'SC011', name: '洛阳城', type: 'scenario', era: '汉', tags: ['都城','汉'], attributes: { political: 2, economic: 2, military: 1, cultural: 3 }, description: '神都' },
  { id: 'SC012', name: '大都城', type: 'scenario', era: '元', tags: ['都城','元'], attributes: { political: 2, economic: 3, military: 1, cultural: 2 }, description: '忽必烈建' },
  { id: 'SC013', name: '紫禁城', type: 'scenario', era: '明', tags: ['宫殿','明'], attributes: { political: 3, economic: 1, military: 0, cultural: 2 }, description: '皇权象征' },
  { id: 'SC014', name: '大运河畔', type: 'scenario', era: '隋', tags: ['水利','隋'], attributes: { political: 0, economic: 4, military: 0, cultural: 1 }, description: '南北动脉' },
  { id: 'SC015', name: '天府平原', type: 'scenario', era: '秦', tags: ['农业','秦'], attributes: { political: 0, economic: 4, military: 0, cultural: 1 }, description: '都江堰灌区' },
  { id: 'SC016', name: '江南水乡', type: 'scenario', era: '宋', tags: ['农业','宋'], attributes: { political: 0, economic: 3, military: 0, cultural: 2 }, description: '苏湖熟天下足' },
  { id: 'SC017', name: '边关长城', type: 'scenario', era: '秦', tags: ['防御','秦'], attributes: { political: 0, economic: 0, military: 3, cultural: 1 }, description: '万里长城' },
  { id: 'SC018', name: '玉门关', type: 'scenario', era: '汉', tags: ['关口','汉'], attributes: { political: 0, economic: 1, military: 2, cultural: 1 }, description: '春风不度' },
  { id: 'SC019', name: '漠北草原', type: 'scenario', era: '汉', tags: ['战场','汉'], attributes: { political: 0, economic: 0, military: 3, cultural: 0 }, description: '逐匈奴' },
  { id: 'SC020', name: '朝堂', type: 'scenario', era: '通用', tags: ['政治','通用'], attributes: { political: 3, economic: 0, military: 0, cultural: 1 }, description: '权力中心' },
  { id: 'SC021', name: '边疆大营', type: 'scenario', era: '通用', tags: ['军事','通用'], attributes: { political: 0, economic: 0, military: 3, cultural: 0 }, description: '驻军之地' },
  { id: 'SC022', name: '市舶司', type: 'scenario', era: '宋', tags: ['海关','宋'], attributes: { political: 0, economic: 3, military: 0, cultural: 1 }, description: '海上贸易' },
  { id: 'SC023', name: '盐铁官营', type: 'scenario', era: '汉', tags: ['制度','汉'], attributes: { political: 2, economic: 3, military: 0, cultural: 0 }, description: '国家垄断' },
  { id: 'SC024', name: '均田制', type: 'scenario', era: '北魏', tags: ['制度','北魏'], attributes: { political: 2, economic: 3, military: 0, cultural: 0 }, description: '授田于民' },
  { id: 'SC025', name: '府兵制', type: 'scenario', era: '北周', tags: ['制度','北周'], attributes: { political: 1, economic: 0, military: 3, cultural: 0 }, description: '兵农合一' },
  { id: 'SC026', name: '募兵制', type: 'scenario', era: '宋', tags: ['制度','宋'], attributes: { political: 0, economic: 0, military: 2, cultural: 0 }, description: '职业军队' },
  { id: 'SC027', name: '一条鞭法', type: 'scenario', era: '明', tags: ['制度','明'], attributes: { political: 2, economic: 4, military: 0, cultural: 0 }, description: '张居正' },
  { id: 'SC028', name: '摊丁入亩', type: 'scenario', era: '清', tags: ['制度','清'], attributes: { political: 3, economic: 3, military: 0, cultural: 0 }, description: '雍正' },
  { id: 'SC029', name: '军机处', type: 'scenario', era: '清', tags: ['制度','清'], attributes: { political: 3, economic: 0, military: 1, cultural: 0 }, description: '皇帝秘书' },
  { id: 'SC030', name: '内阁', type: 'scenario', era: '明', tags: ['制度','明'], attributes: { political: 2, economic: 0, military: 0, cultural: 1 }, description: '票拟权' },
  { id: 'SC031', name: '藩镇', type: 'scenario', era: '唐', tags: ['制度','唐'], attributes: { political: -1, economic: 0, military: 2, cultural: 0 }, description: '割据隐患' },
  { id: 'SC032', name: '党争', type: 'scenario', era: '宋', tags: ['政治','宋'], attributes: { political: -2, economic: 0, military: 0, cultural: 0 }, description: '新旧党争' },
  { id: 'SC033', name: '变法风云', type: 'scenario', era: '宋', tags: ['改革','宋'], attributes: { political: 3, economic: 2, military: 0, cultural: 1 }, description: '王安石' },
  { id: 'SC034', name: '改土归流', type: 'scenario', era: '清', tags: ['改革','清'], attributes: { political: 3, economic: 1, military: 1, cultural: 0 }, description: '雍正' },
  { id: 'SC035', name: '洋务运动', type: 'scenario', era: '清', tags: ['改革','清'], attributes: { political: 1, economic: 2, military: 2, cultural: 1 }, description: '师夷长技' },
  { id: 'SC036', name: '戊戌变法', type: 'scenario', era: '清', tags: ['改革','清'], attributes: { political: 3, economic: 0, military: 0, cultural: 2 }, description: '百日维新' },
  { id: 'SC037', name: '辛亥革命', type: 'scenario', era: '近代', tags: ['革命','近代'], attributes: { political: 4, economic: 1, military: 1, cultural: 2 }, description: '推翻帝制' },
  { id: 'SC038', name: '五四运动', type: 'scenario', era: '近代', tags: ['运动','近代'], attributes: { political: 1, economic: 0, military: 0, cultural: 4 }, description: '新文化' },
  { id: 'SC039', name: '百家争鸣', type: 'scenario', era: '春秋', tags: ['思想','春秋'], attributes: { political: 0, economic: 0, military: 0, cultural: 5 }, description: '诸子百家' },
  { id: 'SC040', name: '焚书坑儒', type: 'scenario', era: '秦', tags: ['事件','秦'], attributes: { political: -2, economic: 0, military: 0, cultural: -3 }, description: '文化灾难' },
  { id: 'SC041', name: '白帝城', type: 'scenario', era: '三国', tags: ['蜀'], attributes: { political: 0, economic: 0, military: 1, cultural: 2 }, description: '刘备托孤之处' },
  { id: 'SC042', name: '滕王阁', type: 'scenario', era: '唐', tags: ['唐'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '江南三大名楼之一' },
  { id: 'SC043', name: '醉翁亭', type: 'scenario', era: '宋', tags: ['宋'], attributes: { political: 0, economic: 0, military: 0, cultural: 3 }, description: '欧阳修《醉翁亭记》中的名亭' },
  { id: 'SC044', name: '马嵬坡', type: 'scenario', era: '唐', tags: ['唐'], attributes: { political: 0, economic: 0, military: 0, cultural: 3 }, description: '杨贵妃香消玉殒之地' },
  { id: 'SC045', name: '桃花庵', type: 'scenario', era: '明', tags: ['明'], attributes: { political: 0, economic: 0, military: 0, cultural: 3 }, description: '唐伯虎隐居作画之处' },
  { id: 'SC046', name: '沈园', type: 'scenario', era: '宋', tags: ['宋'], attributes: { political: 0, economic: 0, military: 0, cultural: 3 }, description: '陆游与唐婉的爱情绝唱' },
  { id: 'SC047', name: '兰亭', type: 'scenario', era: '晋', tags: ['晋'], attributes: { political: 0, economic: 0, military: 0, cultural: 4 }, description: '书圣王羲之曲水流觞之处' },
];

// ===== 事件卡 (40张) =====
export const EVENT_CARDS: Card[] = [
  { id: 'EV001', name: '商鞅变法', type: 'event', era: '秦', tags: ['改革','秦'], attributes: { political: 4, economic: 3, military: 3, cultural: 1 }, description: '富国强兵' },
  { id: 'EV002', name: '秦始皇统一', type: 'event', era: '秦', tags: ['统一','秦'], attributes: { political: 5, economic: 2, military: 5, cultural: 1 }, description: '六王毕' },
  { id: 'EV003', name: '焚书坑儒', type: 'event', era: '秦', tags: ['迫害','秦'], attributes: { political: 1, economic: 0, military: 0, cultural: -3 }, description: '文化灾难' },
  { id: 'EV004', name: '楚汉相争', type: 'event', era: '汉', tags: ['战争','汉'], attributes: { political: 0, economic: 0, military: 3, cultural: 1 }, description: '四年鏖战' },
  { id: 'EV005', name: '文景之治', type: 'event', era: '汉', tags: ['治世','汉'], attributes: { political: 4, economic: 4, military: 1, cultural: 2 }, description: '休养生息' },
  { id: 'EV006', name: '汉武帝北伐', type: 'event', era: '汉', tags: ['战争','汉'], attributes: { political: 2, economic: 0, military: 5, cultural: 0 }, description: '逐匈奴' },
  { id: 'EV007', name: '张骞通西域', type: 'event', era: '汉', tags: ['探险','汉'], attributes: { political: 0, economic: 3, military: 0, cultural: 2 }, description: '凿空' },
  { id: 'EV008', name: '王莽改制', type: 'event', era: '新', tags: ['改革','新'], attributes: { political: 1, economic: 2, military: 0, cultural: 0 }, description: '理想失败' },
  { id: 'EV009', name: '光武中兴', type: 'event', era: '东汉', tags: ['治世','东汉'], attributes: { political: 4, economic: 3, military: 3, cultural: 2 }, description: '汉室复兴' },
  { id: 'EV010', name: '黄巾起义', type: 'event', era: '汉', tags: ['叛乱','汉'], attributes: { political: -2, economic: 0, military: 1, cultural: 0 }, description: '苍天已死' },
  { id: 'EV011', name: '官渡之战', type: 'event', era: '三国', tags: ['战争','三国'], attributes: { political: 0, economic: 0, military: 4, cultural: 0 }, description: '曹操胜' },
  { id: 'EV012', name: '赤壁之战', type: 'event', era: '三国', tags: ['战争','三国'], attributes: { political: 0, economic: 0, military: 5, cultural: 1 }, description: '三分天下' },
  { id: 'EV013', name: '三国鼎立', type: 'event', era: '三国', tags: ['政治','三国'], attributes: { political: 3, economic: 2, military: 3, cultural: 2 }, description: '魏蜀吴' },
  { id: 'EV014', name: '八王之乱', type: 'event', era: '晋', tags: ['内乱','晋'], attributes: { political: -3, economic: 0, military: 0, cultural: 0 }, description: '五胡乱华' },
  { id: 'EV015', name: '淝水之战', type: 'event', era: '晋', tags: ['战争','晋'], attributes: { political: 0, economic: 0, military: 5, cultural: 1 }, description: '以少胜多' },
  { id: 'EV016', name: '孝文帝改革', type: 'event', era: '北魏', tags: ['改革','北魏'], attributes: { political: 4, economic: 2, military: 0, cultural: 4 }, description: '汉化' },
  { id: 'EV017', name: '隋朝统一', type: 'event', era: '隋', tags: ['统一','隋'], attributes: { political: 4, economic: 2, military: 3, cultural: 1 }, description: '再统天下' },
  { id: 'EV018', name: '开凿大运河', type: 'event', era: '隋', tags: ['工程','隋'], attributes: { political: 0, economic: 5, military: 0, cultural: 1 }, description: '南北通' },
  { id: 'EV019', name: '创立科举', type: 'event', era: '隋', tags: ['制度','隋'], attributes: { political: 4, economic: 0, military: 0, cultural: 2 }, description: '打破门阀' },
  { id: 'EV020', name: '玄武门之变', type: 'event', era: '唐', tags: ['政变','唐'], attributes: { political: 4, economic: 0, military: 3, cultural: 0 }, description: '李世民' },
  { id: 'EV021', name: '贞观之治', type: 'event', era: '唐', tags: ['治世','唐'], attributes: { political: 5, economic: 4, military: 4, cultural: 4 }, description: '盛世巅峰' },
  { id: 'EV022', name: '开元盛世', type: 'event', era: '唐', tags: ['治世','唐'], attributes: { political: 5, economic: 5, military: 3, cultural: 5 }, description: '盛极一时' },
  { id: 'EV023', name: '安史之乱', type: 'event', era: '唐', tags: ['叛乱','唐'], attributes: { political: -3, economic: 0, military: 2, cultural: 0 }, description: '盛转衰' },
  { id: 'EV024', name: '黄巢起义', type: 'event', era: '唐', tags: ['叛乱','唐'], attributes: { political: -2, economic: 0, military: 1, cultural: 0 }, description: '满城尽带' },
  { id: 'EV025', name: '陈桥兵变', type: 'event', era: '宋', tags: ['政变','宋'], attributes: { political: 3, economic: 0, military: 2, cultural: 0 }, description: '黄袍加身' },
  { id: 'EV026', name: '杯酒释兵权', type: 'event', era: '宋', tags: ['政治','宋'], attributes: { political: 4, economic: 0, military: 0, cultural: 0 }, description: '收兵权' },
  { id: 'EV027', name: '澶渊之盟', type: 'event', era: '宋', tags: ['和约','宋'], attributes: { political: 2, economic: 1, military: 0, cultural: 0 }, description: '岁币换和平' },
  { id: 'EV028', name: '王安石变法', type: 'event', era: '宋', tags: ['改革','宋'], attributes: { political: 5, economic: 4, military: 1, cultural: 2 }, description: '熙宁变法' },
  { id: 'EV029', name: '靖康之耻', type: 'event', era: '宋', tags: ['灾难','宋'], attributes: { political: -3, economic: 0, military: 2, cultural: 0 }, description: '二帝北狩' },
  { id: 'EV030', name: '岳飞北伐', type: 'event', era: '宋', tags: ['战争','宋'], attributes: { political: 0, economic: 0, military: 4, cultural: 1 }, description: '直捣黄龙' },
  { id: 'EV031', name: '蒙古西征', type: 'event', era: '元', tags: ['战争','元'], attributes: { political: 0, economic: 0, military: 5, cultural: 0 }, description: '横扫欧亚' },
  { id: 'EV032', name: '元朝建立', type: 'event', era: '元', tags: ['统一','元'], attributes: { political: 3, economic: 2, military: 4, cultural: 1 }, description: '大元' },
  { id: 'EV033', name: '红巾军起义', type: 'event', era: '元', tags: ['叛乱','元'], attributes: { political: -2, economic: 0, military: 1, cultural: 0 }, description: '石人一只眼' },
  { id: 'EV034', name: '明朝建立', type: 'event', era: '明', tags: ['统一','明'], attributes: { political: 4, economic: 3, military: 3, cultural: 2 }, description: '洪武' },
  { id: 'EV035', name: '郑和下西洋', type: 'event', era: '明', tags: ['航海','明'], attributes: { political: 0, economic: 5, military: 1, cultural: 2 }, description: '宝船舰队' },
  { id: 'EV036', name: '土木堡之变', type: 'event', era: '明', tags: ['灾难','明'], attributes: { political: -2, economic: 0, military: 2, cultural: 0 }, description: '英宗被俘' },
  { id: 'EV037', name: '北京保卫战', type: 'event', era: '明', tags: ['战争','明'], attributes: { political: 2, economic: 0, military: 5, cultural: 1 }, description: '于谦' },
  { id: 'EV038', name: '张居正改革', type: 'event', era: '明', tags: ['改革','明'], attributes: { political: 5, economic: 5, military: 1, cultural: 2 }, description: '一条鞭法' },
  { id: 'EV039', name: '鸦片战争', type: 'event', era: '清', tags: ['战争','清'], attributes: { political: -2, economic: 0, military: 1, cultural: 0 }, description: '近代开端' },
  { id: 'EV040', name: '辛亥革命', type: 'event', era: '近代', tags: ['革命','近代'], attributes: { political: 5, economic: 1, military: 3, cultural: 3 }, description: '帝制终结' },
];

// 全部卡牌合并
export const ALL_CARDS: Card[] = [
  ...CHARACTER_CARDS,
  ...ITEM_CARDS,
  ...SCENARIO_CARDS,
  ...EVENT_CARDS,
];

// 按ID查找卡牌
export function getCardById(id: string): Card | undefined {
  return ALL_CARDS.find(c => c.id === id);
}

// ===== 关卡时代 → 卡牌时代映射 =====
// 确保时代过滤严格准确，唐朝关卡不会出现隋朝卡牌
const ERA_MAP: Record<string, string[]> = {
  '秦': ['秦'],
  '汉': ['汉', '东汉', '楚'],
  '三国': ['三国', '魏', '蜀', '吴'],
  '晋': ['晋'],
  '南北朝': ['南北朝', '北魏'],
  '隋': ['隋'],
  '唐': ['唐'],
  '宋': ['宋', '北宋', '南宋'],
  '元': ['元'],
  '明': ['明'],
  '清': ['清'],
  '近代': ['近代'],
  '宋元': ['宋', '北宋', '南宋', '元'],
  '明清': ['明', '清'],
  '全时代': ['秦', '汉', '东汉', '楚', '三国', '魏', '蜀', '吴', '晋', '南北朝', '北魏', '隋', '唐', '宋', '北宋', '南宋', '元', '明', '清', '近代', '春秋', '周', '商'],
};

// 按时代筛选卡牌
export function getCardsByEra(era: string): Card[] {
  const validEras = ERA_MAP[era];
  if (!validEras) return [];
  return ALL_CARDS.filter(c => validEras.includes(c.era));
}

// 按类型筛选
export function getCardsByType(type: Card['type']): Card[] {
  return ALL_CARDS.filter(c => c.type === type);
}
